### PR TITLE
Bugfix 404 redirects

### PR DESCRIPTION
**Pull request by sjpaige**
Fix per slack conversations. High priority.

### CODE REVIEW

**Comment by dylankershaw** [comment]
Looks like there's a lot of commits in here. Does it need a rebase?

**Review by dylankershaw — APPROVED** [review]

**Comment by sjpaige** [comment]
> Looks like there's a lot of commits in here. Does it need a rebase?

I think part of it is that Katie and I were having issues with prod commits and staging commits after the launch, so we were trying to base new features off of master instead of staging to alleviate it. Should we rebase staging on master/main/prod then?

**Comment by dylankershaw** [comment]
Yea I think that’s a good idea. Ideally main should only ever get commits that have been through staging first.

**Comment by dylankershaw** [comment]
Ya sure I’ll do that now in a separate branch, which should fix the diff for this branch.

**Pull request merged**
