### PR TITLE
Givingtuesday landing page

### PR DESCRIPTION
**Pull request by GlennStreetman**
### Ticket(s)

[2385 Social Media icons](https://airtable.com/appfJZShN8K4tcWHU/tblXQZfKPAJIjV4cL/viw3SG6YqydrR1Nwg/rechlGkxPYgqXU8Ln/fldZAQHzPZY6QXDQ6?copyLinkToCellOrRecordOrigin=gridView)

-   [2385 Editing Social Icons](https://airtable.com/appfJZShN8K4tcWHU/tblXQZfKPAJIjV4cL/viw3SG6YqydrR1Nwg/rechlGkxPYgqXU8Ln/fldZAQHzPZY6QXDQ6?copyLinkToCellOrRecordOrigin=gridView)

### Type of change

_Please delete any options that are not relevant_

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

### Screenshots
No visual change
### Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation (if applicable)
-   [x] My changes generate no new warnings
-   [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by GlennStreetman** [comment]
<meta> Picture won't show up in Facebook or LinkedIn pop-ups until deployed to live.

**Comment by ShepleySound** [comment]
Great work! Looks like the social pop-ups are working on the Amplify preview. I would like to find a way to make the home banner a bit more responsive though. It ends up looking like this on small screen/mobile -

image

**Comment by ShepleySound** [comment]
Also, can I remove the standalone "Donate" button on the landing page if we have the sticky button at the top?
image

**Review by stuttskl — CHANGES_REQUESTED** [review]
Looks good! Please see my comments, as they are mainly highlighting typos

**Comment by IsaiahPetrichor** [comment]
> Also, can I remove the standalone "Donate" button on the landing page if we have the sticky button at the top? image

Sounds fine with me 🤷

**Review by stuttskl — APPROVED** [review]

**Pull request merged**
